# Generated by Django 3.1.4 on 2020-12-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id_angajat', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('salariu', models.PositiveIntegerField()),
                ('data_angajarii', models.DateField()),
            ],
            options={
                'db_table': 'angajat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id_cabinet', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('specializare_cabinet', models.CharField(max_length=30, unique=True)),
                ('nr_cabinet', models.PositiveIntegerField(unique=True)),
                ('etaj', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cabinet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Internare',
            fields=[
                ('id_internare', models.AutoField(primary_key=True, serialize=False)),
                ('data_internare', models.DateField()),
                ('data_externare', models.DateField(blank=True, null=True)),
                ('salon', models.PositiveIntegerField()),
                ('etaj_salon', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'internare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('cod_parafa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('specializare', models.CharField(max_length=55)),
                ('grad_profesional', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'medic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_medicament', models.AutoField(primary_key=True, serialize=False)),
                ('nume_medicament', models.CharField(max_length=30)),
                ('firma', models.CharField(max_length=30)),
                ('unitate_masura', models.CharField(max_length=10)),
                ('cantitate', models.FloatField()),
            ],
            options={
                'db_table': 'medicament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('cnp', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasterii', models.DateField()),
                ('nr_asigurare', models.CharField(blank=True, max_length=20, null=True)),
                ('parola_cont', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'pacient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('nume_post', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProceduraMedicala',
            fields=[
                ('id_procedura', models.AutoField(primary_key=True, serialize=False)),
                ('nume_procedura', models.CharField(max_length=150, unique=True)),
                ('pret', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'procedura_medicala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProceduriInternare',
            fields=[
                ('id_proc_int', models.AutoField(primary_key=True, serialize=False)),
                ('data_incepere_procedura', models.DateTimeField()),
                ('data_terminare_procedura', models.DateTimeField()),
            ],
            options={
                'db_table': 'proceduri_internare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectie',
            fields=[
                ('id_sectie', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nume_sectie', models.CharField(max_length=30, unique=True)),
                ('nr_paturi', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'sectie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratament',
            fields=[
                ('id_tratament', models.AutoField(primary_key=True, serialize=False)),
                ('data_prescriere', models.DateField()),
                ('diagnostic', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'tratament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultatie',
            fields=[
                ('cod_parafa', models.OneToOneField(db_column='cod_parafa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app1.medic')),
            ],
            options={
                'db_table': 'consultatie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaMedicamente',
            fields=[
                ('id_medicament', models.OneToOneField(db_column='id_medicament', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app1.medicament')),
                ('doza', models.FloatField()),
                ('odata_la', models.PositiveIntegerField()),
                ('data_incepere', models.DateField()),
                ('data_intrerupere', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_medicamente',
                'managed': False,
            },
        ),
    ]
