# Generated by Django 3.1.4 on 2021-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_compus',
            fields=[
                ('id_angajat', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id_post', models.PositiveIntegerField()),
                ('nume_post', models.CharField(max_length=30, unique=True)),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('salariu', models.PositiveIntegerField()),
                ('data_angajarii', models.DateField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
