# Generated by Django 3.1.4 on 2021-01-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_view_compus'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.PositiveIntegerField()),
                ('salariu_maxim', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
